package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.CabinetLogs;
import com.pxccn.PxcDali2.server.database.model.CabinetLogsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CabinetLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=CabinetLogsSqlProvider.class, method="countByExample")
    long countByExample(CabinetLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @DeleteProvider(type=CabinetLogsSqlProvider.class, method="deleteByExample")
    int deleteByExample(CabinetLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Delete({
        "delete from cabinet_logs",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Insert({
        "insert into cabinet_logs (id, cabinet_ID, ",
        "ts, level, className, ",
        "methodName, msg, ",
        "errorStack)",
        "values (#{id,jdbcType=BIGINT}, #{cabinetId,jdbcType=INTEGER}, ",
        "#{ts,jdbcType=TIMESTAMP}, #{level,jdbcType=VARCHAR}, #{classname,jdbcType=VARCHAR}, ",
        "#{methodname,jdbcType=VARCHAR}, #{msg,jdbcType=VARCHAR}, ",
        "#{errorstack,jdbcType=VARCHAR})"
    })
    int insert(CabinetLogs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @InsertProvider(type=CabinetLogsSqlProvider.class, method="insertSelective")
    int insertSelective(CabinetLogs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=CabinetLogsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="cabinet_ID", property="cabinetId", jdbcType=JdbcType.INTEGER),
        @Result(column="ts", property="ts", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="level", property="level", jdbcType=JdbcType.VARCHAR),
        @Result(column="className", property="classname", jdbcType=JdbcType.VARCHAR),
        @Result(column="methodName", property="methodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="msg", property="msg", jdbcType=JdbcType.VARCHAR),
        @Result(column="errorStack", property="errorstack", jdbcType=JdbcType.VARCHAR)
    })
    List<CabinetLogs> selectByExample(CabinetLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Select({
        "select",
        "id, cabinet_ID, ts, level, className, methodName, msg, errorStack",
        "from cabinet_logs",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="cabinet_ID", property="cabinetId", jdbcType=JdbcType.INTEGER),
        @Result(column="ts", property="ts", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="level", property="level", jdbcType=JdbcType.VARCHAR),
        @Result(column="className", property="classname", jdbcType=JdbcType.VARCHAR),
        @Result(column="methodName", property="methodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="msg", property="msg", jdbcType=JdbcType.VARCHAR),
        @Result(column="errorStack", property="errorstack", jdbcType=JdbcType.VARCHAR)
    })
    CabinetLogs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=CabinetLogsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") CabinetLogs row, @Param("example") CabinetLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=CabinetLogsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") CabinetLogs row, @Param("example") CabinetLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=CabinetLogsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CabinetLogs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Update({
        "update cabinet_logs",
        "set cabinet_ID = #{cabinetId,jdbcType=INTEGER},",
          "ts = #{ts,jdbcType=TIMESTAMP},",
          "level = #{level,jdbcType=VARCHAR},",
          "className = #{classname,jdbcType=VARCHAR},",
          "methodName = #{methodname,jdbcType=VARCHAR},",
          "msg = #{msg,jdbcType=VARCHAR},",
          "errorStack = #{errorstack,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CabinetLogs row);
}