package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.CabinetLogs;
import com.pxccn.PxcDali2.server.database.model.CabinetLogsExample.Criteria;
import com.pxccn.PxcDali2.server.database.model.CabinetLogsExample.Criterion;
import com.pxccn.PxcDali2.server.database.model.CabinetLogsExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CabinetLogsSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String countByExample(CabinetLogsExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cabinet_logs");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String deleteByExample(CabinetLogsExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cabinet_logs");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String insertSelective(CabinetLogs row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cabinet_logs");
        
        if (row.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (row.getCabinetId() != null) {
            sql.VALUES("cabinet_ID", "#{cabinetId,jdbcType=INTEGER}");
        }
        
        if (row.getTs() != null) {
            sql.VALUES("ts", "#{ts,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLevel() != null) {
            sql.VALUES("level", "#{level,jdbcType=VARCHAR}");
        }
        
        if (row.getClassname() != null) {
            sql.VALUES("className", "#{classname,jdbcType=VARCHAR}");
        }
        
        if (row.getMethodname() != null) {
            sql.VALUES("methodName", "#{methodname,jdbcType=VARCHAR}");
        }
        
        if (row.getMsg() != null) {
            sql.VALUES("msg", "#{msg,jdbcType=VARCHAR}");
        }
        
        if (row.getErrorstack() != null) {
            sql.VALUES("errorStack", "#{errorstack,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String selectByExample(CabinetLogsExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cabinet_ID");
        sql.SELECT("ts");
        sql.SELECT("level");
        sql.SELECT("className");
        sql.SELECT("methodName");
        sql.SELECT("msg");
        sql.SELECT("errorStack");
        sql.FROM("cabinet_logs");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CabinetLogs row = (CabinetLogs) parameter.get("row");
        CabinetLogsExample example = (CabinetLogsExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cabinet_logs");
        
        if (row.getId() != null) {
            sql.SET("id = #{row.id,jdbcType=BIGINT}");
        }
        
        if (row.getCabinetId() != null) {
            sql.SET("cabinet_ID = #{row.cabinetId,jdbcType=INTEGER}");
        }
        
        if (row.getTs() != null) {
            sql.SET("ts = #{row.ts,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLevel() != null) {
            sql.SET("level = #{row.level,jdbcType=VARCHAR}");
        }
        
        if (row.getClassname() != null) {
            sql.SET("className = #{row.classname,jdbcType=VARCHAR}");
        }
        
        if (row.getMethodname() != null) {
            sql.SET("methodName = #{row.methodname,jdbcType=VARCHAR}");
        }
        
        if (row.getMsg() != null) {
            sql.SET("msg = #{row.msg,jdbcType=VARCHAR}");
        }
        
        if (row.getErrorstack() != null) {
            sql.SET("errorStack = #{row.errorstack,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cabinet_logs");
        
        sql.SET("id = #{row.id,jdbcType=BIGINT}");
        sql.SET("cabinet_ID = #{row.cabinetId,jdbcType=INTEGER}");
        sql.SET("ts = #{row.ts,jdbcType=TIMESTAMP}");
        sql.SET("level = #{row.level,jdbcType=VARCHAR}");
        sql.SET("className = #{row.classname,jdbcType=VARCHAR}");
        sql.SET("methodName = #{row.methodname,jdbcType=VARCHAR}");
        sql.SET("msg = #{row.msg,jdbcType=VARCHAR}");
        sql.SET("errorStack = #{row.errorstack,jdbcType=VARCHAR}");
        
        CabinetLogsExample example = (CabinetLogsExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String updateByPrimaryKeySelective(CabinetLogs row) {
        SQL sql = new SQL();
        sql.UPDATE("cabinet_logs");
        
        if (row.getCabinetId() != null) {
            sql.SET("cabinet_ID = #{cabinetId,jdbcType=INTEGER}");
        }
        
        if (row.getTs() != null) {
            sql.SET("ts = #{ts,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLevel() != null) {
            sql.SET("level = #{level,jdbcType=VARCHAR}");
        }
        
        if (row.getClassname() != null) {
            sql.SET("className = #{classname,jdbcType=VARCHAR}");
        }
        
        if (row.getMethodname() != null) {
            sql.SET("methodName = #{methodname,jdbcType=VARCHAR}");
        }
        
        if (row.getMsg() != null) {
            sql.SET("msg = #{msg,jdbcType=VARCHAR}");
        }
        
        if (row.getErrorstack() != null) {
            sql.SET("errorStack = #{errorstack,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    protected void applyWhere(SQL sql, CabinetLogsExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}