package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.CabinetV2;
import com.pxccn.PxcDali2.server.database.model.CabinetV2Example.Criteria;
import com.pxccn.PxcDali2.server.database.model.CabinetV2Example.Criterion;
import com.pxccn.PxcDali2.server.database.model.CabinetV2Example;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CabinetV2SqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String countByExample(CabinetV2Example example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cabinet_V2");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String deleteByExample(CabinetV2Example example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cabinet_V2");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String insertSelective(CabinetV2 row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cabinet_V2");
        
        if (row.getCabinetId() != null) {
            sql.VALUES("cabinet_ID", "#{cabinetId,jdbcType=INTEGER}");
        }
        
        if (row.getSyncflag() != null) {
            sql.VALUES("syncFlag", "#{syncflag,jdbcType=BIT}");
        }
        
        if (row.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=NVARCHAR}");
        }
        
        if (row.getIpAddress() != null) {
            sql.VALUES("ip_address", "#{ipAddress,jdbcType=VARCHAR}");
        }
        
        if (row.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=NVARCHAR}");
        }
        
        if (row.getVersion() != null) {
            sql.VALUES("version", "#{version,jdbcType=NVARCHAR}");
        }
        
        if (row.getLastalive() != null) {
            sql.VALUES("lastAlive", "#{lastalive,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLastsync() != null) {
            sql.VALUES("lastSync", "#{lastsync,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLocationBuilding() != null) {
            sql.VALUES("location_building", "#{locationBuilding,jdbcType=NVARCHAR}");
        }
        
        if (row.getLocationFloor() != null) {
            sql.VALUES("location_floor", "#{locationFloor,jdbcType=NVARCHAR}");
        }
        
        if (row.getLocationZone() != null) {
            sql.VALUES("location_zone", "#{locationZone,jdbcType=NVARCHAR}");
        }
        
        if (row.getAxisX() != null) {
            sql.VALUES("axis_x", "#{axisX,jdbcType=INTEGER}");
        }
        
        if (row.getAxisY() != null) {
            sql.VALUES("axis_y", "#{axisY,jdbcType=INTEGER}");
        }
        
        if (row.getAxisZ() != null) {
            sql.VALUES("axis_z", "#{axisZ,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String selectByExample(CabinetV2Example example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("cabinet_ID");
        } else {
            sql.SELECT("cabinet_ID");
        }
        sql.SELECT("syncFlag");
        sql.SELECT("name");
        sql.SELECT("ip_address");
        sql.SELECT("description");
        sql.SELECT("version");
        sql.SELECT("lastAlive");
        sql.SELECT("lastSync");
        sql.SELECT("location_building");
        sql.SELECT("location_floor");
        sql.SELECT("location_zone");
        sql.SELECT("axis_x");
        sql.SELECT("axis_y");
        sql.SELECT("axis_z");
        sql.FROM("cabinet_V2");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CabinetV2 row = (CabinetV2) parameter.get("row");
        CabinetV2Example example = (CabinetV2Example) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cabinet_V2");
        
        if (row.getCabinetId() != null) {
            sql.SET("cabinet_ID = #{row.cabinetId,jdbcType=INTEGER}");
        }
        
        if (row.getSyncflag() != null) {
            sql.SET("syncFlag = #{row.syncflag,jdbcType=BIT}");
        }
        
        if (row.getName() != null) {
            sql.SET("name = #{row.name,jdbcType=NVARCHAR}");
        }
        
        if (row.getIpAddress() != null) {
            sql.SET("ip_address = #{row.ipAddress,jdbcType=VARCHAR}");
        }
        
        if (row.getDescription() != null) {
            sql.SET("description = #{row.description,jdbcType=NVARCHAR}");
        }
        
        if (row.getVersion() != null) {
            sql.SET("version = #{row.version,jdbcType=NVARCHAR}");
        }
        
        if (row.getLastalive() != null) {
            sql.SET("lastAlive = #{row.lastalive,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLastsync() != null) {
            sql.SET("lastSync = #{row.lastsync,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLocationBuilding() != null) {
            sql.SET("location_building = #{row.locationBuilding,jdbcType=NVARCHAR}");
        }
        
        if (row.getLocationFloor() != null) {
            sql.SET("location_floor = #{row.locationFloor,jdbcType=NVARCHAR}");
        }
        
        if (row.getLocationZone() != null) {
            sql.SET("location_zone = #{row.locationZone,jdbcType=NVARCHAR}");
        }
        
        if (row.getAxisX() != null) {
            sql.SET("axis_x = #{row.axisX,jdbcType=INTEGER}");
        }
        
        if (row.getAxisY() != null) {
            sql.SET("axis_y = #{row.axisY,jdbcType=INTEGER}");
        }
        
        if (row.getAxisZ() != null) {
            sql.SET("axis_z = #{row.axisZ,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cabinet_V2");
        
        sql.SET("cabinet_ID = #{row.cabinetId,jdbcType=INTEGER}");
        sql.SET("syncFlag = #{row.syncflag,jdbcType=BIT}");
        sql.SET("name = #{row.name,jdbcType=NVARCHAR}");
        sql.SET("ip_address = #{row.ipAddress,jdbcType=VARCHAR}");
        sql.SET("description = #{row.description,jdbcType=NVARCHAR}");
        sql.SET("version = #{row.version,jdbcType=NVARCHAR}");
        sql.SET("lastAlive = #{row.lastalive,jdbcType=TIMESTAMP}");
        sql.SET("lastSync = #{row.lastsync,jdbcType=TIMESTAMP}");
        sql.SET("location_building = #{row.locationBuilding,jdbcType=NVARCHAR}");
        sql.SET("location_floor = #{row.locationFloor,jdbcType=NVARCHAR}");
        sql.SET("location_zone = #{row.locationZone,jdbcType=NVARCHAR}");
        sql.SET("axis_x = #{row.axisX,jdbcType=INTEGER}");
        sql.SET("axis_y = #{row.axisY,jdbcType=INTEGER}");
        sql.SET("axis_z = #{row.axisZ,jdbcType=INTEGER}");
        
        CabinetV2Example example = (CabinetV2Example) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String updateByPrimaryKeySelective(CabinetV2 row) {
        SQL sql = new SQL();
        sql.UPDATE("cabinet_V2");
        
        if (row.getSyncflag() != null) {
            sql.SET("syncFlag = #{syncflag,jdbcType=BIT}");
        }
        
        if (row.getName() != null) {
            sql.SET("name = #{name,jdbcType=NVARCHAR}");
        }
        
        if (row.getIpAddress() != null) {
            sql.SET("ip_address = #{ipAddress,jdbcType=VARCHAR}");
        }
        
        if (row.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=NVARCHAR}");
        }
        
        if (row.getVersion() != null) {
            sql.SET("version = #{version,jdbcType=NVARCHAR}");
        }
        
        if (row.getLastalive() != null) {
            sql.SET("lastAlive = #{lastalive,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLastsync() != null) {
            sql.SET("lastSync = #{lastsync,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLocationBuilding() != null) {
            sql.SET("location_building = #{locationBuilding,jdbcType=NVARCHAR}");
        }
        
        if (row.getLocationFloor() != null) {
            sql.SET("location_floor = #{locationFloor,jdbcType=NVARCHAR}");
        }
        
        if (row.getLocationZone() != null) {
            sql.SET("location_zone = #{locationZone,jdbcType=NVARCHAR}");
        }
        
        if (row.getAxisX() != null) {
            sql.SET("axis_x = #{axisX,jdbcType=INTEGER}");
        }
        
        if (row.getAxisY() != null) {
            sql.SET("axis_y = #{axisY,jdbcType=INTEGER}");
        }
        
        if (row.getAxisZ() != null) {
            sql.SET("axis_z = #{axisZ,jdbcType=INTEGER}");
        }
        
        sql.WHERE("cabinet_ID = #{cabinetId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    protected void applyWhere(SQL sql, CabinetV2Example example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}