package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.CabinetModuleV2;
import com.pxccn.PxcDali2.server.database.model.CabinetModuleV2Example.Criteria;
import com.pxccn.PxcDali2.server.database.model.CabinetModuleV2Example.Criterion;
import com.pxccn.PxcDali2.server.database.model.CabinetModuleV2Example;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CabinetModuleV2SqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String countByExample(CabinetModuleV2Example example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cabinet_module_V2");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String deleteByExample(CabinetModuleV2Example example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cabinet_module_V2");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String insertSelective(CabinetModuleV2 row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cabinet_module_V2");
        
        if (row.getCabinetId() != null) {
            sql.VALUES("cabinet_ID", "#{cabinetId,jdbcType=INTEGER}");
        }
        
        if (row.getTerminalIndex() != null) {
            sql.VALUES("terminal_Index", "#{terminalIndex,jdbcType=INTEGER}");
        }
        
        if (row.getSiblingIndex() != null) {
            sql.VALUES("sibling_Index", "#{siblingIndex,jdbcType=INTEGER}");
        }
        
        if (row.getModuleType() != null) {
            sql.VALUES("module_type", "#{moduleType,jdbcType=VARCHAR}");
        }
        
        if (row.getModuleName() != null) {
            sql.VALUES("module_name", "#{moduleName,jdbcType=VARCHAR}");
        }
        
        if (row.getAdditioninfo() != null) {
            sql.VALUES("additionInfo", "#{additioninfo,jdbcType=NVARCHAR}");
        }
        
        if (row.getAuditLightCount() != null) {
            sql.VALUES("audit_light_count", "#{auditLightCount,jdbcType=INTEGER}");
        }
        
        if (row.getAuditErrorLightCount() != null) {
            sql.VALUES("audit_error_light_count", "#{auditErrorLightCount,jdbcType=INTEGER}");
        }
        
        if (row.getAuditTime() != null) {
            sql.VALUES("audit_time", "#{auditTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String selectByExample(CabinetModuleV2Example example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("cabinet_ID");
        } else {
            sql.SELECT("cabinet_ID");
        }
        sql.SELECT("terminal_Index");
        sql.SELECT("sibling_Index");
        sql.SELECT("module_type");
        sql.SELECT("module_name");
        sql.SELECT("additionInfo");
        sql.SELECT("audit_light_count");
        sql.SELECT("audit_error_light_count");
        sql.SELECT("audit_time");
        sql.FROM("cabinet_module_V2");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CabinetModuleV2 row = (CabinetModuleV2) parameter.get("row");
        CabinetModuleV2Example example = (CabinetModuleV2Example) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cabinet_module_V2");
        
        if (row.getCabinetId() != null) {
            sql.SET("cabinet_ID = #{row.cabinetId,jdbcType=INTEGER}");
        }
        
        if (row.getTerminalIndex() != null) {
            sql.SET("terminal_Index = #{row.terminalIndex,jdbcType=INTEGER}");
        }
        
        if (row.getSiblingIndex() != null) {
            sql.SET("sibling_Index = #{row.siblingIndex,jdbcType=INTEGER}");
        }
        
        if (row.getModuleType() != null) {
            sql.SET("module_type = #{row.moduleType,jdbcType=VARCHAR}");
        }
        
        if (row.getModuleName() != null) {
            sql.SET("module_name = #{row.moduleName,jdbcType=VARCHAR}");
        }
        
        if (row.getAdditioninfo() != null) {
            sql.SET("additionInfo = #{row.additioninfo,jdbcType=NVARCHAR}");
        }
        
        if (row.getAuditLightCount() != null) {
            sql.SET("audit_light_count = #{row.auditLightCount,jdbcType=INTEGER}");
        }
        
        if (row.getAuditErrorLightCount() != null) {
            sql.SET("audit_error_light_count = #{row.auditErrorLightCount,jdbcType=INTEGER}");
        }
        
        if (row.getAuditTime() != null) {
            sql.SET("audit_time = #{row.auditTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cabinet_module_V2");
        
        sql.SET("cabinet_ID = #{row.cabinetId,jdbcType=INTEGER}");
        sql.SET("terminal_Index = #{row.terminalIndex,jdbcType=INTEGER}");
        sql.SET("sibling_Index = #{row.siblingIndex,jdbcType=INTEGER}");
        sql.SET("module_type = #{row.moduleType,jdbcType=VARCHAR}");
        sql.SET("module_name = #{row.moduleName,jdbcType=VARCHAR}");
        sql.SET("additionInfo = #{row.additioninfo,jdbcType=NVARCHAR}");
        sql.SET("audit_light_count = #{row.auditLightCount,jdbcType=INTEGER}");
        sql.SET("audit_error_light_count = #{row.auditErrorLightCount,jdbcType=INTEGER}");
        sql.SET("audit_time = #{row.auditTime,jdbcType=TIMESTAMP}");
        
        CabinetModuleV2Example example = (CabinetModuleV2Example) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String updateByPrimaryKeySelective(CabinetModuleV2 row) {
        SQL sql = new SQL();
        sql.UPDATE("cabinet_module_V2");
        
        if (row.getSiblingIndex() != null) {
            sql.SET("sibling_Index = #{siblingIndex,jdbcType=INTEGER}");
        }
        
        if (row.getModuleType() != null) {
            sql.SET("module_type = #{moduleType,jdbcType=VARCHAR}");
        }
        
        if (row.getModuleName() != null) {
            sql.SET("module_name = #{moduleName,jdbcType=VARCHAR}");
        }
        
        if (row.getAdditioninfo() != null) {
            sql.SET("additionInfo = #{additioninfo,jdbcType=NVARCHAR}");
        }
        
        if (row.getAuditLightCount() != null) {
            sql.SET("audit_light_count = #{auditLightCount,jdbcType=INTEGER}");
        }
        
        if (row.getAuditErrorLightCount() != null) {
            sql.SET("audit_error_light_count = #{auditErrorLightCount,jdbcType=INTEGER}");
        }
        
        if (row.getAuditTime() != null) {
            sql.SET("audit_time = #{auditTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("cabinet_ID = #{cabinetId,jdbcType=INTEGER}");
        sql.WHERE("terminal_Index = #{terminalIndex,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    protected void applyWhere(SQL sql, CabinetModuleV2Example example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}