package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.CabinetModuleV2;
import com.pxccn.PxcDali2.server.database.model.CabinetModuleV2Example;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CabinetModuleV2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=CabinetModuleV2SqlProvider.class, method="countByExample")
    long countByExample(CabinetModuleV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @DeleteProvider(type=CabinetModuleV2SqlProvider.class, method="deleteByExample")
    int deleteByExample(CabinetModuleV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Delete({
        "delete from cabinet_module_V2",
        "where cabinet_ID = #{cabinetId,jdbcType=INTEGER}",
          "and terminal_Index = #{terminalIndex,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("cabinetId") Integer cabinetId, @Param("terminalIndex") Integer terminalIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Insert({
        "insert into cabinet_module_V2 (cabinet_ID, terminal_Index, ",
        "sibling_Index, module_type, ",
        "module_name, additionInfo, ",
        "audit_light_count, audit_error_light_count, ",
        "audit_time)",
        "values (#{cabinetId,jdbcType=INTEGER}, #{terminalIndex,jdbcType=INTEGER}, ",
        "#{siblingIndex,jdbcType=INTEGER}, #{moduleType,jdbcType=VARCHAR}, ",
        "#{moduleName,jdbcType=VARCHAR}, #{additioninfo,jdbcType=NVARCHAR}, ",
        "#{auditLightCount,jdbcType=INTEGER}, #{auditErrorLightCount,jdbcType=INTEGER}, ",
        "#{auditTime,jdbcType=TIMESTAMP})"
    })
    int insert(CabinetModuleV2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @InsertProvider(type=CabinetModuleV2SqlProvider.class, method="insertSelective")
    int insertSelective(CabinetModuleV2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=CabinetModuleV2SqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="cabinet_ID", property="cabinetId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="terminal_Index", property="terminalIndex", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="sibling_Index", property="siblingIndex", jdbcType=JdbcType.INTEGER),
        @Result(column="module_type", property="moduleType", jdbcType=JdbcType.VARCHAR),
        @Result(column="module_name", property="moduleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="additionInfo", property="additioninfo", jdbcType=JdbcType.NVARCHAR),
        @Result(column="audit_light_count", property="auditLightCount", jdbcType=JdbcType.INTEGER),
        @Result(column="audit_error_light_count", property="auditErrorLightCount", jdbcType=JdbcType.INTEGER),
        @Result(column="audit_time", property="auditTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CabinetModuleV2> selectByExample(CabinetModuleV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Select({
        "select",
        "cabinet_ID, terminal_Index, sibling_Index, module_type, module_name, additionInfo, ",
        "audit_light_count, audit_error_light_count, audit_time",
        "from cabinet_module_V2",
        "where cabinet_ID = #{cabinetId,jdbcType=INTEGER}",
          "and terminal_Index = #{terminalIndex,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="cabinet_ID", property="cabinetId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="terminal_Index", property="terminalIndex", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="sibling_Index", property="siblingIndex", jdbcType=JdbcType.INTEGER),
        @Result(column="module_type", property="moduleType", jdbcType=JdbcType.VARCHAR),
        @Result(column="module_name", property="moduleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="additionInfo", property="additioninfo", jdbcType=JdbcType.NVARCHAR),
        @Result(column="audit_light_count", property="auditLightCount", jdbcType=JdbcType.INTEGER),
        @Result(column="audit_error_light_count", property="auditErrorLightCount", jdbcType=JdbcType.INTEGER),
        @Result(column="audit_time", property="auditTime", jdbcType=JdbcType.TIMESTAMP)
    })
    CabinetModuleV2 selectByPrimaryKey(@Param("cabinetId") Integer cabinetId, @Param("terminalIndex") Integer terminalIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=CabinetModuleV2SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") CabinetModuleV2 row, @Param("example") CabinetModuleV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=CabinetModuleV2SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") CabinetModuleV2 row, @Param("example") CabinetModuleV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=CabinetModuleV2SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CabinetModuleV2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Update({
        "update cabinet_module_V2",
        "set sibling_Index = #{siblingIndex,jdbcType=INTEGER},",
          "module_type = #{moduleType,jdbcType=VARCHAR},",
          "module_name = #{moduleName,jdbcType=VARCHAR},",
          "additionInfo = #{additioninfo,jdbcType=NVARCHAR},",
          "audit_light_count = #{auditLightCount,jdbcType=INTEGER},",
          "audit_error_light_count = #{auditErrorLightCount,jdbcType=INTEGER},",
          "audit_time = #{auditTime,jdbcType=TIMESTAMP}",
        "where cabinet_ID = #{cabinetId,jdbcType=INTEGER}",
          "and terminal_Index = #{terminalIndex,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CabinetModuleV2 row);
}