package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.LightsV2;
import com.pxccn.PxcDali2.server.database.model.LightsV2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LightsV2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    long countByExample(LightsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    int deleteByExample(LightsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    int deleteByPrimaryKey(String lightuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    int insert(LightsV2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    int insertSelective(LightsV2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    List<LightsV2> selectByExample(LightsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    LightsV2 selectByPrimaryKey(String lightuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    int updateByExampleSelective(@Param("row") LightsV2 row, @Param("example") LightsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    int updateByExample(@Param("row") LightsV2 row, @Param("example") LightsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    int updateByPrimaryKeySelective(LightsV2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    int updateByPrimaryKey(LightsV2 row);
}