package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.RoomLightMapV3;
import com.pxccn.PxcDali2.server.database.model.RoomLightMapV3Example;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RoomLightMapV3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=RoomLightMapV3SqlProvider.class, method="countByExample")
    long countByExample(RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @DeleteProvider(type=RoomLightMapV3SqlProvider.class, method="deleteByExample")
    int deleteByExample(RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Delete({
        "delete from room_light_map_V3",
        "where lightUUID = #{lightuuid,jdbcType=CHAR}",
          "and roomUUID = #{roomuuid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(@Param("lightuuid") String lightuuid, @Param("roomuuid") String roomuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Insert({
        "insert into room_light_map_V3 (lightUUID, roomUUID, ",
        "cabinet_ID)",
        "values (#{lightuuid,jdbcType=CHAR}, #{roomuuid,jdbcType=CHAR}, ",
        "#{cabinetId,jdbcType=INTEGER})"
    })
    int insert(RoomLightMapV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @InsertProvider(type=RoomLightMapV3SqlProvider.class, method="insertSelective")
    int insertSelective(RoomLightMapV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=RoomLightMapV3SqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="lightUUID", property="lightuuid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="roomUUID", property="roomuuid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="cabinet_ID", property="cabinetId", jdbcType=JdbcType.INTEGER)
    })
    List<RoomLightMapV3> selectByExample(RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Select({
        "select",
        "lightUUID, roomUUID, cabinet_ID",
        "from room_light_map_V3",
        "where lightUUID = #{lightuuid,jdbcType=CHAR}",
          "and roomUUID = #{roomuuid,jdbcType=CHAR}"
    })
    @Results({
        @Result(column="lightUUID", property="lightuuid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="roomUUID", property="roomuuid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="cabinet_ID", property="cabinetId", jdbcType=JdbcType.INTEGER)
    })
    RoomLightMapV3 selectByPrimaryKey(@Param("lightuuid") String lightuuid, @Param("roomuuid") String roomuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=RoomLightMapV3SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") RoomLightMapV3 row, @Param("example") RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=RoomLightMapV3SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") RoomLightMapV3 row, @Param("example") RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=RoomLightMapV3SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RoomLightMapV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Update({
        "update room_light_map_V3",
        "set cabinet_ID = #{cabinetId,jdbcType=INTEGER}",
        "where lightUUID = #{lightuuid,jdbcType=CHAR}",
          "and roomUUID = #{roomuuid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(RoomLightMapV3 row);
}