package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.RoomUnitV3;
import com.pxccn.PxcDali2.server.database.model.RoomUnitV3Example;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RoomUnitV3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=RoomUnitV3SqlProvider.class, method="countByExample")
    long countByExample(RoomUnitV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @DeleteProvider(type=RoomUnitV3SqlProvider.class, method="deleteByExample")
    int deleteByExample(RoomUnitV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Delete({
        "delete from room_unit_V3",
        "where roomUUID = #{roomuuid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String roomuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Insert({
        "insert into room_unit_V3 (roomUUID, name, ",
        "description, building, ",
        "floor, zone, axis_x, ",
        "axis_y, axis_z, status)",
        "values (#{roomuuid,jdbcType=CHAR}, #{name,jdbcType=NVARCHAR}, ",
        "#{description,jdbcType=NVARCHAR}, #{building,jdbcType=NVARCHAR}, ",
        "#{floor,jdbcType=NVARCHAR}, #{zone,jdbcType=NVARCHAR}, #{axisX,jdbcType=INTEGER}, ",
        "#{axisY,jdbcType=INTEGER}, #{axisZ,jdbcType=INTEGER}, #{status,jdbcType=INTEGER})"
    })
    int insert(RoomUnitV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @InsertProvider(type=RoomUnitV3SqlProvider.class, method="insertSelective")
    int insertSelective(RoomUnitV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=RoomUnitV3SqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="roomUUID", property="roomuuid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.NVARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.NVARCHAR),
        @Result(column="building", property="building", jdbcType=JdbcType.NVARCHAR),
        @Result(column="floor", property="floor", jdbcType=JdbcType.NVARCHAR),
        @Result(column="zone", property="zone", jdbcType=JdbcType.NVARCHAR),
        @Result(column="axis_x", property="axisX", jdbcType=JdbcType.INTEGER),
        @Result(column="axis_y", property="axisY", jdbcType=JdbcType.INTEGER),
        @Result(column="axis_z", property="axisZ", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    List<RoomUnitV3> selectByExample(RoomUnitV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Select({
        "select",
        "roomUUID, name, description, building, floor, zone, axis_x, axis_y, axis_z, ",
        "status",
        "from room_unit_V3",
        "where roomUUID = #{roomuuid,jdbcType=CHAR}"
    })
    @Results({
        @Result(column="roomUUID", property="roomuuid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.NVARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.NVARCHAR),
        @Result(column="building", property="building", jdbcType=JdbcType.NVARCHAR),
        @Result(column="floor", property="floor", jdbcType=JdbcType.NVARCHAR),
        @Result(column="zone", property="zone", jdbcType=JdbcType.NVARCHAR),
        @Result(column="axis_x", property="axisX", jdbcType=JdbcType.INTEGER),
        @Result(column="axis_y", property="axisY", jdbcType=JdbcType.INTEGER),
        @Result(column="axis_z", property="axisZ", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    RoomUnitV3 selectByPrimaryKey(String roomuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=RoomUnitV3SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") RoomUnitV3 row, @Param("example") RoomUnitV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=RoomUnitV3SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") RoomUnitV3 row, @Param("example") RoomUnitV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=RoomUnitV3SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RoomUnitV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Update({
        "update room_unit_V3",
        "set name = #{name,jdbcType=NVARCHAR},",
          "description = #{description,jdbcType=NVARCHAR},",
          "building = #{building,jdbcType=NVARCHAR},",
          "floor = #{floor,jdbcType=NVARCHAR},",
          "zone = #{zone,jdbcType=NVARCHAR},",
          "axis_x = #{axisX,jdbcType=INTEGER},",
          "axis_y = #{axisY,jdbcType=INTEGER},",
          "axis_z = #{axisZ,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER}",
        "where roomUUID = #{roomuuid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(RoomUnitV3 row);
}