package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.RoomTriggerV3;
import com.pxccn.PxcDali2.server.database.model.RoomTriggerV3Example;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RoomTriggerV3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=RoomTriggerV3SqlProvider.class, method="countByExample")
    long countByExample(RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @DeleteProvider(type=RoomTriggerV3SqlProvider.class, method="deleteByExample")
    int deleteByExample(RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Delete({
        "delete from room_trigger_V3",
        "where triggerUUID = #{triggeruuid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String triggeruuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Insert({
        "insert into room_trigger_V3 (triggerUUID, triggerType, ",
        "roomUUID, cabinet_ID, ",
        "triggerConfigure, fb, ",
        "fb2)",
        "values (#{triggeruuid,jdbcType=CHAR}, #{triggertype,jdbcType=VARCHAR}, ",
        "#{roomuuid,jdbcType=CHAR}, #{cabinetId,jdbcType=INTEGER}, ",
        "#{triggerconfigure,jdbcType=NVARCHAR}, #{fb,jdbcType=VARCHAR}, ",
        "#{fb2,jdbcType=NVARCHAR})"
    })
    int insert(RoomTriggerV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @InsertProvider(type=RoomTriggerV3SqlProvider.class, method="insertSelective")
    int insertSelective(RoomTriggerV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @SelectProvider(type=RoomTriggerV3SqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="triggerUUID", property="triggeruuid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="triggerType", property="triggertype", jdbcType=JdbcType.VARCHAR),
        @Result(column="roomUUID", property="roomuuid", jdbcType=JdbcType.CHAR),
        @Result(column="cabinet_ID", property="cabinetId", jdbcType=JdbcType.INTEGER),
        @Result(column="triggerConfigure", property="triggerconfigure", jdbcType=JdbcType.NVARCHAR),
        @Result(column="fb", property="fb", jdbcType=JdbcType.VARCHAR),
        @Result(column="fb2", property="fb2", jdbcType=JdbcType.NVARCHAR)
    })
    List<RoomTriggerV3> selectByExample(RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Select({
        "select",
        "triggerUUID, triggerType, roomUUID, cabinet_ID, triggerConfigure, fb, fb2",
        "from room_trigger_V3",
        "where triggerUUID = #{triggeruuid,jdbcType=CHAR}"
    })
    @Results({
        @Result(column="triggerUUID", property="triggeruuid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="triggerType", property="triggertype", jdbcType=JdbcType.VARCHAR),
        @Result(column="roomUUID", property="roomuuid", jdbcType=JdbcType.CHAR),
        @Result(column="cabinet_ID", property="cabinetId", jdbcType=JdbcType.INTEGER),
        @Result(column="triggerConfigure", property="triggerconfigure", jdbcType=JdbcType.NVARCHAR),
        @Result(column="fb", property="fb", jdbcType=JdbcType.VARCHAR),
        @Result(column="fb2", property="fb2", jdbcType=JdbcType.NVARCHAR)
    })
    RoomTriggerV3 selectByPrimaryKey(String triggeruuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=RoomTriggerV3SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") RoomTriggerV3 row, @Param("example") RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=RoomTriggerV3SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") RoomTriggerV3 row, @Param("example") RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @UpdateProvider(type=RoomTriggerV3SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RoomTriggerV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Update({
        "update room_trigger_V3",
        "set triggerType = #{triggertype,jdbcType=VARCHAR},",
          "roomUUID = #{roomuuid,jdbcType=CHAR},",
          "cabinet_ID = #{cabinetId,jdbcType=INTEGER},",
          "triggerConfigure = #{triggerconfigure,jdbcType=NVARCHAR},",
          "fb = #{fb,jdbcType=VARCHAR},",
          "fb2 = #{fb2,jdbcType=NVARCHAR}",
        "where triggerUUID = #{triggeruuid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(RoomTriggerV3 row);
}