package com.pxccn.PxcDali2.server.database.mapper;

import com.pxccn.PxcDali2.server.database.model.RoomLightMapV3;
import com.pxccn.PxcDali2.server.database.model.RoomLightMapV3Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoomLightMapV3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    long countByExample(RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    int deleteByExample(RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    int deleteByPrimaryKey(@Param("lightuuid") String lightuuid, @Param("roomuuid") String roomuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    int insert(RoomLightMapV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    int insertSelective(RoomLightMapV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    List<RoomLightMapV3> selectByExample(RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    RoomLightMapV3 selectByPrimaryKey(@Param("lightuuid") String lightuuid, @Param("roomuuid") String roomuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    int updateByExampleSelective(@Param("row") RoomLightMapV3 row, @Param("example") RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    int updateByExample(@Param("row") RoomLightMapV3 row, @Param("example") RoomLightMapV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    int updateByPrimaryKeySelective(RoomLightMapV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_light_map_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    int updateByPrimaryKey(RoomLightMapV3 row);
}