LcsServer:
  name: "LCS-1"
  ver: "0.1"
  timeServer: true # 是否负责全场控制器时间同步任务
  dataBaseMaxPoolSize: 16

spring:
  datasource:
    name: LCS_DB
    url: "jdbc:sqlserver://172.14.1.13:1433;database=BMW_LightsControl;encrypt=false;trustServerCertificate=true;"
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  rabbitmq:
    publisher-returns: true
    publisher-confirm-type: correlated
    virtual-host: LCS
    host: 172.14.0.5  #mq服务器ip,默认为localhost
    port: 5672          #mq服务器port,默认为5672
    username: srv     #mq服务器username,默认为gust
    password: srv     #mq服务器password,默认为guest
    listener:
      type: direct
#logging:
#  level:
#    org.springframework.amqp.rabbit.listener.DirectReplyToMessageListenerContainer: warn
#    org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer: warn
#    com.pxccn.PxcDali2: debug
#    com.pxccn.PxcDali2.server.mq: info
#    com.pxccn.PxcDali2.server.framework: info
#    com.pxccn.PxcDali2.server.space.lights.Dali2Light: trace
#    com.pxccn.PxcDali2.server.space.cabinets.CabinetsManager: debug
#    com.pxccn.PxcDali2.server.space.cabinets.Cabinet: debug
#    com.pxccn.PxcDali2.server.space.v3Rooms: trace
#    com.pxccn.PxcDali2.server.service.opcua: trace
#    com.pxccn.PxcDali2.server.service.opcua.UaAlarmEventService: debug
#    com.pxccn.PxcDali2.server.service.rpc.impl.CabinetRequestServiceImpl: debug

prosys:
  ApplicationName: LCS_Server
  ApplicationUri: "urn:hostname:OPCUA:LCS_Server"
  ProductUri: "urn:pxc.com:OPCUA:LCS_Server"
  ApplicationCertificateStore: PKI/CA
  ApplicationIssuerCertificateStore: PKI/CA/issuers
  UserCertificateStore: USERS_PKI/CA
  UserIssuerCertificateStore: USERS_PKI/CA/issuers
  Port: 52520



