LcsServer:
  name: "LCS-221" # 应保证集群中唯一
  ver: "0.1"
  timeServer: true # 是否负责全场控制器时间同步任务
  autoDiscoverChangedRoom: true # 是否负责自动扫描V3room表status字段
  autoUpdateOnlineCabinetLightsAndRoomsInfo: true # 是否负责自动执行全场控制器灯具与房间数据上送（兼顾清空边缘测状态缓存）
  dataBaseMaxPoolSize: 16 # 数据库线程数量
  offlineThreshold: 30000 # 缺少心跳多久后判定为离线

  enableDebugEvent: true
  debugEventSeverity: 0
  successEventSeverity: 100
  failureEventSeverity: 1000

  updateAuditInDatabase: true

  otaSourcePath: C:\LCS_OTA\PxcDali2-rt.jar
  otaTargetPath: /home/sysmik/niagara/modules

  logService: true

spring:
  datasource:
    name: LCS_DB
    url: "jdbc:sqlserver://172.14.1.11:1433;database=BMW_LightsControl;encrypt=false;trustServerCertificate=true;"
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  rabbitmq:
    publisher-returns: true
    publisher-confirm-type: correlated
    virtual-host: LCS
    host: 172.14.0.5  #mq服务器ip,默认为localhost
    port: 5672        #mq服务器port,默认为5672
    username: srv     #mq服务器username,默认为gust
    password: srv     #mq服务器password,默认为guest
    listener:
      type: direct
#logging:
#  level:
#    org.springframework.amqp.rabbit.listener.DirectReplyToMessageListenerContainer: warn
#    org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer: warn
#    com.pxccn.PxcDali2: debug
#    com.pxccn.PxcDali2.server.mq: info
#    com.pxccn.PxcDali2.server.framework: info
#    com.pxccn.PxcDali2.server.space.lights.Dali2Light: trace
#    com.pxccn.PxcDali2.server.space.cabinets.CabinetsManager: debug
#    com.pxccn.PxcDali2.server.space.cabinets.Cabinet: debug
#    com.pxccn.PxcDali2.server.space.v3Rooms: trace
#    com.pxccn.PxcDali2.server.service.opcua: trace
#    com.pxccn.PxcDali2.server.service.opcua.UaAlarmEventService: debug
#    com.pxccn.PxcDali2.server.service.rpc.impl.CabinetRequestServiceImpl: debug

prosys:
  ApplicationName: LCS_Server
  ApplicationUri: "urn:hostname:OPCUA:LCS_Server"
  ProductUri: "urn:pxc.com:OPCUA:LCS_Server"
  ApplicationCertificateStore: PKI/CA
  ApplicationIssuerCertificateStore: PKI/CA/issuers
  UserCertificateStore: USERS_PKI/CA
  UserIssuerCertificateStore: USERS_PKI/CA/issuers
  Port: 52522



