package com.pxccn.PxcDali2.server.model;

import java.util.ArrayList;
import java.util.List;

public class LightsV2Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public LightsV2Example() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLightuuidIsNull() {
            addCriterion("lightUUID is null");
            return (Criteria) this;
        }

        public Criteria andLightuuidIsNotNull() {
            addCriterion("lightUUID is not null");
            return (Criteria) this;
        }

        public Criteria andLightuuidEqualTo(String value) {
            addCriterion("lightUUID =", value, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidNotEqualTo(String value) {
            addCriterion("lightUUID <>", value, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidGreaterThan(String value) {
            addCriterion("lightUUID >", value, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidGreaterThanOrEqualTo(String value) {
            addCriterion("lightUUID >=", value, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidLessThan(String value) {
            addCriterion("lightUUID <", value, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidLessThanOrEqualTo(String value) {
            addCriterion("lightUUID <=", value, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidLike(String value) {
            addCriterion("lightUUID like", value, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidNotLike(String value) {
            addCriterion("lightUUID not like", value, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidIn(List<String> values) {
            addCriterion("lightUUID in", values, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidNotIn(List<String> values) {
            addCriterion("lightUUID not in", values, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidBetween(String value1, String value2) {
            addCriterion("lightUUID between", value1, value2, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andLightuuidNotBetween(String value1, String value2) {
            addCriterion("lightUUID not between", value1, value2, "lightuuid");
            return (Criteria) this;
        }

        public Criteria andSyncflagIsNull() {
            addCriterion("syncFlag is null");
            return (Criteria) this;
        }

        public Criteria andSyncflagIsNotNull() {
            addCriterion("syncFlag is not null");
            return (Criteria) this;
        }

        public Criteria andSyncflagEqualTo(Boolean value) {
            addCriterion("syncFlag =", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagNotEqualTo(Boolean value) {
            addCriterion("syncFlag <>", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagGreaterThan(Boolean value) {
            addCriterion("syncFlag >", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("syncFlag >=", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagLessThan(Boolean value) {
            addCriterion("syncFlag <", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagLessThanOrEqualTo(Boolean value) {
            addCriterion("syncFlag <=", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagIn(List<Boolean> values) {
            addCriterion("syncFlag in", values, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagNotIn(List<Boolean> values) {
            addCriterion("syncFlag not in", values, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagBetween(Boolean value1, Boolean value2) {
            addCriterion("syncFlag between", value1, value2, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("syncFlag not between", value1, value2, "syncflag");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIsNull() {
            addCriterion("cabinet_ID is null");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIsNotNull() {
            addCriterion("cabinet_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCabinetIdEqualTo(Integer value) {
            addCriterion("cabinet_ID =", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotEqualTo(Integer value) {
            addCriterion("cabinet_ID <>", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdGreaterThan(Integer value) {
            addCriterion("cabinet_ID >", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cabinet_ID >=", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdLessThan(Integer value) {
            addCriterion("cabinet_ID <", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdLessThanOrEqualTo(Integer value) {
            addCriterion("cabinet_ID <=", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIn(List<Integer> values) {
            addCriterion("cabinet_ID in", values, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotIn(List<Integer> values) {
            addCriterion("cabinet_ID not in", values, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdBetween(Integer value1, Integer value2) {
            addCriterion("cabinet_ID between", value1, value2, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cabinet_ID not between", value1, value2, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andBusindexIsNull() {
            addCriterion("busIndex is null");
            return (Criteria) this;
        }

        public Criteria andBusindexIsNotNull() {
            addCriterion("busIndex is not null");
            return (Criteria) this;
        }

        public Criteria andBusindexEqualTo(Integer value) {
            addCriterion("busIndex =", value, "busindex");
            return (Criteria) this;
        }

        public Criteria andBusindexNotEqualTo(Integer value) {
            addCriterion("busIndex <>", value, "busindex");
            return (Criteria) this;
        }

        public Criteria andBusindexGreaterThan(Integer value) {
            addCriterion("busIndex >", value, "busindex");
            return (Criteria) this;
        }

        public Criteria andBusindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("busIndex >=", value, "busindex");
            return (Criteria) this;
        }

        public Criteria andBusindexLessThan(Integer value) {
            addCriterion("busIndex <", value, "busindex");
            return (Criteria) this;
        }

        public Criteria andBusindexLessThanOrEqualTo(Integer value) {
            addCriterion("busIndex <=", value, "busindex");
            return (Criteria) this;
        }

        public Criteria andBusindexIn(List<Integer> values) {
            addCriterion("busIndex in", values, "busindex");
            return (Criteria) this;
        }

        public Criteria andBusindexNotIn(List<Integer> values) {
            addCriterion("busIndex not in", values, "busindex");
            return (Criteria) this;
        }

        public Criteria andBusindexBetween(Integer value1, Integer value2) {
            addCriterion("busIndex between", value1, value2, "busindex");
            return (Criteria) this;
        }

        public Criteria andBusindexNotBetween(Integer value1, Integer value2) {
            addCriterion("busIndex not between", value1, value2, "busindex");
            return (Criteria) this;
        }

        public Criteria andBustypeIsNull() {
            addCriterion("busType is null");
            return (Criteria) this;
        }

        public Criteria andBustypeIsNotNull() {
            addCriterion("busType is not null");
            return (Criteria) this;
        }

        public Criteria andBustypeEqualTo(String value) {
            addCriterion("busType =", value, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeNotEqualTo(String value) {
            addCriterion("busType <>", value, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeGreaterThan(String value) {
            addCriterion("busType >", value, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeGreaterThanOrEqualTo(String value) {
            addCriterion("busType >=", value, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeLessThan(String value) {
            addCriterion("busType <", value, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeLessThanOrEqualTo(String value) {
            addCriterion("busType <=", value, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeLike(String value) {
            addCriterion("busType like", value, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeNotLike(String value) {
            addCriterion("busType not like", value, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeIn(List<String> values) {
            addCriterion("busType in", values, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeNotIn(List<String> values) {
            addCriterion("busType not in", values, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeBetween(String value1, String value2) {
            addCriterion("busType between", value1, value2, "bustype");
            return (Criteria) this;
        }

        public Criteria andBustypeNotBetween(String value1, String value2) {
            addCriterion("busType not between", value1, value2, "bustype");
            return (Criteria) this;
        }

        public Criteria andShortaddressIsNull() {
            addCriterion("shortAddress is null");
            return (Criteria) this;
        }

        public Criteria andShortaddressIsNotNull() {
            addCriterion("shortAddress is not null");
            return (Criteria) this;
        }

        public Criteria andShortaddressEqualTo(Integer value) {
            addCriterion("shortAddress =", value, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andShortaddressNotEqualTo(Integer value) {
            addCriterion("shortAddress <>", value, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andShortaddressGreaterThan(Integer value) {
            addCriterion("shortAddress >", value, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andShortaddressGreaterThanOrEqualTo(Integer value) {
            addCriterion("shortAddress >=", value, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andShortaddressLessThan(Integer value) {
            addCriterion("shortAddress <", value, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andShortaddressLessThanOrEqualTo(Integer value) {
            addCriterion("shortAddress <=", value, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andShortaddressIn(List<Integer> values) {
            addCriterion("shortAddress in", values, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andShortaddressNotIn(List<Integer> values) {
            addCriterion("shortAddress not in", values, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andShortaddressBetween(Integer value1, Integer value2) {
            addCriterion("shortAddress between", value1, value2, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andShortaddressNotBetween(Integer value1, Integer value2) {
            addCriterion("shortAddress not between", value1, value2, "shortaddress");
            return (Criteria) this;
        }

        public Criteria andAxisXIsNull() {
            addCriterion("axis_x is null");
            return (Criteria) this;
        }

        public Criteria andAxisXIsNotNull() {
            addCriterion("axis_x is not null");
            return (Criteria) this;
        }

        public Criteria andAxisXEqualTo(Integer value) {
            addCriterion("axis_x =", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXNotEqualTo(Integer value) {
            addCriterion("axis_x <>", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXGreaterThan(Integer value) {
            addCriterion("axis_x >", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_x >=", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXLessThan(Integer value) {
            addCriterion("axis_x <", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXLessThanOrEqualTo(Integer value) {
            addCriterion("axis_x <=", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXIn(List<Integer> values) {
            addCriterion("axis_x in", values, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXNotIn(List<Integer> values) {
            addCriterion("axis_x not in", values, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXBetween(Integer value1, Integer value2) {
            addCriterion("axis_x between", value1, value2, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_x not between", value1, value2, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisYIsNull() {
            addCriterion("axis_y is null");
            return (Criteria) this;
        }

        public Criteria andAxisYIsNotNull() {
            addCriterion("axis_y is not null");
            return (Criteria) this;
        }

        public Criteria andAxisYEqualTo(Integer value) {
            addCriterion("axis_y =", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYNotEqualTo(Integer value) {
            addCriterion("axis_y <>", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYGreaterThan(Integer value) {
            addCriterion("axis_y >", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_y >=", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYLessThan(Integer value) {
            addCriterion("axis_y <", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYLessThanOrEqualTo(Integer value) {
            addCriterion("axis_y <=", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYIn(List<Integer> values) {
            addCriterion("axis_y in", values, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYNotIn(List<Integer> values) {
            addCriterion("axis_y not in", values, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYBetween(Integer value1, Integer value2) {
            addCriterion("axis_y between", value1, value2, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_y not between", value1, value2, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisZIsNull() {
            addCriterion("axis_z is null");
            return (Criteria) this;
        }

        public Criteria andAxisZIsNotNull() {
            addCriterion("axis_z is not null");
            return (Criteria) this;
        }

        public Criteria andAxisZEqualTo(Integer value) {
            addCriterion("axis_z =", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZNotEqualTo(Integer value) {
            addCriterion("axis_z <>", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZGreaterThan(Integer value) {
            addCriterion("axis_z >", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_z >=", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZLessThan(Integer value) {
            addCriterion("axis_z <", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZLessThanOrEqualTo(Integer value) {
            addCriterion("axis_z <=", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZIn(List<Integer> values) {
            addCriterion("axis_z in", values, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZNotIn(List<Integer> values) {
            addCriterion("axis_z not in", values, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZBetween(Integer value1, Integer value2) {
            addCriterion("axis_z between", value1, value2, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_z not between", value1, value2, "axisZ");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lights_V2
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 25 20:07:24 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lights_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}