package com.pxccn.PxcDali2.server.mapper;

import com.pxccn.PxcDali2.server.model.PointsV2;
import com.pxccn.PxcDali2.server.model.PointsV2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PointsV2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    long countByExample(PointsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int deleteByExample(PointsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int deleteByPrimaryKey(@Param("cabinetId") Integer cabinetId, @Param("pointstr") String pointstr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int insert(PointsV2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int insertSelective(PointsV2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    List<PointsV2> selectByExample(PointsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    PointsV2 selectByPrimaryKey(@Param("cabinetId") Integer cabinetId, @Param("pointstr") String pointstr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int updateByExampleSelective(@Param("row") PointsV2 row, @Param("example") PointsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int updateByExample(@Param("row") PointsV2 row, @Param("example") PointsV2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int updateByPrimaryKeySelective(PointsV2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int updateByPrimaryKey(PointsV2 row);
}