package com.pxccn.PxcDali2.server.mapper;

import com.pxccn.PxcDali2.server.model.RoomTriggerV3;
import com.pxccn.PxcDali2.server.model.RoomTriggerV3Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomTriggerV3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    long countByExample(RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int deleteByExample(RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int deleteByPrimaryKey(String triggeruuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int insert(RoomTriggerV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int insertSelective(RoomTriggerV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    List<RoomTriggerV3> selectByExample(RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    RoomTriggerV3 selectByPrimaryKey(String triggeruuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int updateByExampleSelective(@Param("row") RoomTriggerV3 row, @Param("example") RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int updateByExample(@Param("row") RoomTriggerV3 row, @Param("example") RoomTriggerV3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int updateByPrimaryKeySelective(RoomTriggerV3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sat Jun 25 20:07:24 CST 2022
     */
    int updateByPrimaryKey(RoomTriggerV3 row);
}