package com.pxccn.PxcDali2.server.database.model;

import java.io.Serializable;

public class CabinetModuleV2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_module_V2.cabinet_ID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer cabinetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_module_V2.terminal_Index
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer terminalIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_module_V2.sibling_Index
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer siblingIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_module_V2.module_type
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String moduleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_module_V2.module_name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_module_V2.additionInfo
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String additioninfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_module_V2.cabinet_ID
     *
     * @return the value of cabinet_module_V2.cabinet_ID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getCabinetId() {
        return cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_module_V2.cabinet_ID
     *
     * @param cabinetId the value for cabinet_module_V2.cabinet_ID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setCabinetId(Integer cabinetId) {
        this.cabinetId = cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_module_V2.terminal_Index
     *
     * @return the value of cabinet_module_V2.terminal_Index
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getTerminalIndex() {
        return terminalIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_module_V2.terminal_Index
     *
     * @param terminalIndex the value for cabinet_module_V2.terminal_Index
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setTerminalIndex(Integer terminalIndex) {
        this.terminalIndex = terminalIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_module_V2.sibling_Index
     *
     * @return the value of cabinet_module_V2.sibling_Index
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getSiblingIndex() {
        return siblingIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_module_V2.sibling_Index
     *
     * @param siblingIndex the value for cabinet_module_V2.sibling_Index
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setSiblingIndex(Integer siblingIndex) {
        this.siblingIndex = siblingIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_module_V2.module_type
     *
     * @return the value of cabinet_module_V2.module_type
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_module_V2.module_type
     *
     * @param moduleType the value for cabinet_module_V2.module_type
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setModuleType(String moduleType) {
        this.moduleType = moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_module_V2.module_name
     *
     * @return the value of cabinet_module_V2.module_name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_module_V2.module_name
     *
     * @param moduleName the value for cabinet_module_V2.module_name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_module_V2.additionInfo
     *
     * @return the value of cabinet_module_V2.additionInfo
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getAdditioninfo() {
        return additioninfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_module_V2.additionInfo
     *
     * @param additioninfo the value for cabinet_module_V2.additionInfo
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAdditioninfo(String additioninfo) {
        this.additioninfo = additioninfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_module_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cabinetId=").append(cabinetId);
        sb.append(", terminalIndex=").append(terminalIndex);
        sb.append(", siblingIndex=").append(siblingIndex);
        sb.append(", moduleType=").append(moduleType);
        sb.append(", moduleName=").append(moduleName);
        sb.append(", additioninfo=").append(additioninfo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}