package com.pxccn.PxcDali2.server.database.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CabinetV2Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public CabinetV2Example() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCabinetIdIsNull() {
            addCriterion("cabinet_ID is null");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIsNotNull() {
            addCriterion("cabinet_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCabinetIdEqualTo(Integer value) {
            addCriterion("cabinet_ID =", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotEqualTo(Integer value) {
            addCriterion("cabinet_ID <>", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdGreaterThan(Integer value) {
            addCriterion("cabinet_ID >", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cabinet_ID >=", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdLessThan(Integer value) {
            addCriterion("cabinet_ID <", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdLessThanOrEqualTo(Integer value) {
            addCriterion("cabinet_ID <=", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIn(List<Integer> values) {
            addCriterion("cabinet_ID in", values, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotIn(List<Integer> values) {
            addCriterion("cabinet_ID not in", values, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdBetween(Integer value1, Integer value2) {
            addCriterion("cabinet_ID between", value1, value2, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cabinet_ID not between", value1, value2, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andSyncflagIsNull() {
            addCriterion("syncFlag is null");
            return (Criteria) this;
        }

        public Criteria andSyncflagIsNotNull() {
            addCriterion("syncFlag is not null");
            return (Criteria) this;
        }

        public Criteria andSyncflagEqualTo(Boolean value) {
            addCriterion("syncFlag =", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagNotEqualTo(Boolean value) {
            addCriterion("syncFlag <>", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagGreaterThan(Boolean value) {
            addCriterion("syncFlag >", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("syncFlag >=", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagLessThan(Boolean value) {
            addCriterion("syncFlag <", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagLessThanOrEqualTo(Boolean value) {
            addCriterion("syncFlag <=", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagIn(List<Boolean> values) {
            addCriterion("syncFlag in", values, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagNotIn(List<Boolean> values) {
            addCriterion("syncFlag not in", values, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagBetween(Boolean value1, Boolean value2) {
            addCriterion("syncFlag between", value1, value2, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("syncFlag not between", value1, value2, "syncflag");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIpAddressIsNull() {
            addCriterion("ip_address is null");
            return (Criteria) this;
        }

        public Criteria andIpAddressIsNotNull() {
            addCriterion("ip_address is not null");
            return (Criteria) this;
        }

        public Criteria andIpAddressEqualTo(String value) {
            addCriterion("ip_address =", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressNotEqualTo(String value) {
            addCriterion("ip_address <>", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressGreaterThan(String value) {
            addCriterion("ip_address >", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ip_address >=", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressLessThan(String value) {
            addCriterion("ip_address <", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressLessThanOrEqualTo(String value) {
            addCriterion("ip_address <=", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressLike(String value) {
            addCriterion("ip_address like", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressNotLike(String value) {
            addCriterion("ip_address not like", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressIn(List<String> values) {
            addCriterion("ip_address in", values, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressNotIn(List<String> values) {
            addCriterion("ip_address not in", values, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressBetween(String value1, String value2) {
            addCriterion("ip_address between", value1, value2, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressNotBetween(String value1, String value2) {
            addCriterion("ip_address not between", value1, value2, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andLastaliveIsNull() {
            addCriterion("lastAlive is null");
            return (Criteria) this;
        }

        public Criteria andLastaliveIsNotNull() {
            addCriterion("lastAlive is not null");
            return (Criteria) this;
        }

        public Criteria andLastaliveEqualTo(Date value) {
            addCriterion("lastAlive =", value, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastaliveNotEqualTo(Date value) {
            addCriterion("lastAlive <>", value, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastaliveGreaterThan(Date value) {
            addCriterion("lastAlive >", value, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastaliveGreaterThanOrEqualTo(Date value) {
            addCriterion("lastAlive >=", value, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastaliveLessThan(Date value) {
            addCriterion("lastAlive <", value, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastaliveLessThanOrEqualTo(Date value) {
            addCriterion("lastAlive <=", value, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastaliveIn(List<Date> values) {
            addCriterion("lastAlive in", values, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastaliveNotIn(List<Date> values) {
            addCriterion("lastAlive not in", values, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastaliveBetween(Date value1, Date value2) {
            addCriterion("lastAlive between", value1, value2, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastaliveNotBetween(Date value1, Date value2) {
            addCriterion("lastAlive not between", value1, value2, "lastalive");
            return (Criteria) this;
        }

        public Criteria andLastsyncIsNull() {
            addCriterion("lastSync is null");
            return (Criteria) this;
        }

        public Criteria andLastsyncIsNotNull() {
            addCriterion("lastSync is not null");
            return (Criteria) this;
        }

        public Criteria andLastsyncEqualTo(Date value) {
            addCriterion("lastSync =", value, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLastsyncNotEqualTo(Date value) {
            addCriterion("lastSync <>", value, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLastsyncGreaterThan(Date value) {
            addCriterion("lastSync >", value, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLastsyncGreaterThanOrEqualTo(Date value) {
            addCriterion("lastSync >=", value, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLastsyncLessThan(Date value) {
            addCriterion("lastSync <", value, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLastsyncLessThanOrEqualTo(Date value) {
            addCriterion("lastSync <=", value, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLastsyncIn(List<Date> values) {
            addCriterion("lastSync in", values, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLastsyncNotIn(List<Date> values) {
            addCriterion("lastSync not in", values, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLastsyncBetween(Date value1, Date value2) {
            addCriterion("lastSync between", value1, value2, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLastsyncNotBetween(Date value1, Date value2) {
            addCriterion("lastSync not between", value1, value2, "lastsync");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingIsNull() {
            addCriterion("location_building is null");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingIsNotNull() {
            addCriterion("location_building is not null");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingEqualTo(String value) {
            addCriterion("location_building =", value, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingNotEqualTo(String value) {
            addCriterion("location_building <>", value, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingGreaterThan(String value) {
            addCriterion("location_building >", value, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingGreaterThanOrEqualTo(String value) {
            addCriterion("location_building >=", value, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingLessThan(String value) {
            addCriterion("location_building <", value, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingLessThanOrEqualTo(String value) {
            addCriterion("location_building <=", value, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingLike(String value) {
            addCriterion("location_building like", value, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingNotLike(String value) {
            addCriterion("location_building not like", value, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingIn(List<String> values) {
            addCriterion("location_building in", values, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingNotIn(List<String> values) {
            addCriterion("location_building not in", values, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingBetween(String value1, String value2) {
            addCriterion("location_building between", value1, value2, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationBuildingNotBetween(String value1, String value2) {
            addCriterion("location_building not between", value1, value2, "locationBuilding");
            return (Criteria) this;
        }

        public Criteria andLocationFloorIsNull() {
            addCriterion("location_floor is null");
            return (Criteria) this;
        }

        public Criteria andLocationFloorIsNotNull() {
            addCriterion("location_floor is not null");
            return (Criteria) this;
        }

        public Criteria andLocationFloorEqualTo(String value) {
            addCriterion("location_floor =", value, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorNotEqualTo(String value) {
            addCriterion("location_floor <>", value, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorGreaterThan(String value) {
            addCriterion("location_floor >", value, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorGreaterThanOrEqualTo(String value) {
            addCriterion("location_floor >=", value, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorLessThan(String value) {
            addCriterion("location_floor <", value, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorLessThanOrEqualTo(String value) {
            addCriterion("location_floor <=", value, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorLike(String value) {
            addCriterion("location_floor like", value, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorNotLike(String value) {
            addCriterion("location_floor not like", value, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorIn(List<String> values) {
            addCriterion("location_floor in", values, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorNotIn(List<String> values) {
            addCriterion("location_floor not in", values, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorBetween(String value1, String value2) {
            addCriterion("location_floor between", value1, value2, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationFloorNotBetween(String value1, String value2) {
            addCriterion("location_floor not between", value1, value2, "locationFloor");
            return (Criteria) this;
        }

        public Criteria andLocationZoneIsNull() {
            addCriterion("location_zone is null");
            return (Criteria) this;
        }

        public Criteria andLocationZoneIsNotNull() {
            addCriterion("location_zone is not null");
            return (Criteria) this;
        }

        public Criteria andLocationZoneEqualTo(String value) {
            addCriterion("location_zone =", value, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneNotEqualTo(String value) {
            addCriterion("location_zone <>", value, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneGreaterThan(String value) {
            addCriterion("location_zone >", value, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneGreaterThanOrEqualTo(String value) {
            addCriterion("location_zone >=", value, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneLessThan(String value) {
            addCriterion("location_zone <", value, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneLessThanOrEqualTo(String value) {
            addCriterion("location_zone <=", value, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneLike(String value) {
            addCriterion("location_zone like", value, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneNotLike(String value) {
            addCriterion("location_zone not like", value, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneIn(List<String> values) {
            addCriterion("location_zone in", values, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneNotIn(List<String> values) {
            addCriterion("location_zone not in", values, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneBetween(String value1, String value2) {
            addCriterion("location_zone between", value1, value2, "locationZone");
            return (Criteria) this;
        }

        public Criteria andLocationZoneNotBetween(String value1, String value2) {
            addCriterion("location_zone not between", value1, value2, "locationZone");
            return (Criteria) this;
        }

        public Criteria andAxisXIsNull() {
            addCriterion("axis_x is null");
            return (Criteria) this;
        }

        public Criteria andAxisXIsNotNull() {
            addCriterion("axis_x is not null");
            return (Criteria) this;
        }

        public Criteria andAxisXEqualTo(Integer value) {
            addCriterion("axis_x =", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXNotEqualTo(Integer value) {
            addCriterion("axis_x <>", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXGreaterThan(Integer value) {
            addCriterion("axis_x >", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_x >=", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXLessThan(Integer value) {
            addCriterion("axis_x <", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXLessThanOrEqualTo(Integer value) {
            addCriterion("axis_x <=", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXIn(List<Integer> values) {
            addCriterion("axis_x in", values, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXNotIn(List<Integer> values) {
            addCriterion("axis_x not in", values, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXBetween(Integer value1, Integer value2) {
            addCriterion("axis_x between", value1, value2, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_x not between", value1, value2, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisYIsNull() {
            addCriterion("axis_y is null");
            return (Criteria) this;
        }

        public Criteria andAxisYIsNotNull() {
            addCriterion("axis_y is not null");
            return (Criteria) this;
        }

        public Criteria andAxisYEqualTo(Integer value) {
            addCriterion("axis_y =", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYNotEqualTo(Integer value) {
            addCriterion("axis_y <>", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYGreaterThan(Integer value) {
            addCriterion("axis_y >", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_y >=", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYLessThan(Integer value) {
            addCriterion("axis_y <", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYLessThanOrEqualTo(Integer value) {
            addCriterion("axis_y <=", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYIn(List<Integer> values) {
            addCriterion("axis_y in", values, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYNotIn(List<Integer> values) {
            addCriterion("axis_y not in", values, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYBetween(Integer value1, Integer value2) {
            addCriterion("axis_y between", value1, value2, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_y not between", value1, value2, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisZIsNull() {
            addCriterion("axis_z is null");
            return (Criteria) this;
        }

        public Criteria andAxisZIsNotNull() {
            addCriterion("axis_z is not null");
            return (Criteria) this;
        }

        public Criteria andAxisZEqualTo(Integer value) {
            addCriterion("axis_z =", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZNotEqualTo(Integer value) {
            addCriterion("axis_z <>", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZGreaterThan(Integer value) {
            addCriterion("axis_z >", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_z >=", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZLessThan(Integer value) {
            addCriterion("axis_z <", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZLessThanOrEqualTo(Integer value) {
            addCriterion("axis_z <=", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZIn(List<Integer> values) {
            addCriterion("axis_z in", values, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZNotIn(List<Integer> values) {
            addCriterion("axis_z not in", values, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZBetween(Integer value1, Integer value2) {
            addCriterion("axis_z between", value1, value2, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_z not between", value1, value2, "axisZ");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cabinet_V2
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 18 10:18:42 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}