package com.pxccn.PxcDali2.server.database.model;

import java.io.Serializable;
import java.util.Date;

public class CabinetLogs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_logs.id
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_logs.cabinet_ID
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    private Integer cabinetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_logs.ts
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    private Date ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_logs.level
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_logs.className
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_logs.methodName
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    private String methodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_logs.msg
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_logs.errorStack
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    private String errorstack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_logs.id
     *
     * @return the value of cabinet_logs.id
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_logs.id
     *
     * @param id the value for cabinet_logs.id
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_logs.cabinet_ID
     *
     * @return the value of cabinet_logs.cabinet_ID
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public Integer getCabinetId() {
        return cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_logs.cabinet_ID
     *
     * @param cabinetId the value for cabinet_logs.cabinet_ID
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public void setCabinetId(Integer cabinetId) {
        this.cabinetId = cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_logs.ts
     *
     * @return the value of cabinet_logs.ts
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_logs.ts
     *
     * @param ts the value for cabinet_logs.ts
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_logs.level
     *
     * @return the value of cabinet_logs.level
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_logs.level
     *
     * @param level the value for cabinet_logs.level
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_logs.className
     *
     * @return the value of cabinet_logs.className
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_logs.className
     *
     * @param classname the value for cabinet_logs.className
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_logs.methodName
     *
     * @return the value of cabinet_logs.methodName
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String getMethodname() {
        return methodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_logs.methodName
     *
     * @param methodname the value for cabinet_logs.methodName
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public void setMethodname(String methodname) {
        this.methodname = methodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_logs.msg
     *
     * @return the value of cabinet_logs.msg
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_logs.msg
     *
     * @param msg the value for cabinet_logs.msg
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_logs.errorStack
     *
     * @return the value of cabinet_logs.errorStack
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public String getErrorstack() {
        return errorstack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_logs.errorStack
     *
     * @param errorstack the value for cabinet_logs.errorStack
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    public void setErrorstack(String errorstack) {
        this.errorstack = errorstack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_logs
     *
     * @mbg.generated Wed Oct 12 09:14:04 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cabinetId=").append(cabinetId);
        sb.append(", ts=").append(ts);
        sb.append(", level=").append(level);
        sb.append(", classname=").append(classname);
        sb.append(", methodname=").append(methodname);
        sb.append(", msg=").append(msg);
        sb.append(", errorstack=").append(errorstack);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}