package com.pxccn.PxcDali2.server.database.model;

import java.io.Serializable;
import java.util.Date;

public class CabinetV2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.cabinet_ID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer cabinetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.syncFlag
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Boolean syncflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.ip_address
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.description
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.version
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.lastAlive
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Date lastalive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.lastSync
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Date lastsync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.location_building
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String locationBuilding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.location_floor
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String locationFloor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.location_zone
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String locationZone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.axis_x
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer axisX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.axis_y
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer axisY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_V2.axis_z
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer axisZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.cabinet_ID
     *
     * @return the value of cabinet_V2.cabinet_ID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getCabinetId() {
        return cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.cabinet_ID
     *
     * @param cabinetId the value for cabinet_V2.cabinet_ID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setCabinetId(Integer cabinetId) {
        this.cabinetId = cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.syncFlag
     *
     * @return the value of cabinet_V2.syncFlag
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Boolean getSyncflag() {
        return syncflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.syncFlag
     *
     * @param syncflag the value for cabinet_V2.syncFlag
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setSyncflag(Boolean syncflag) {
        this.syncflag = syncflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.name
     *
     * @return the value of cabinet_V2.name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.name
     *
     * @param name the value for cabinet_V2.name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.ip_address
     *
     * @return the value of cabinet_V2.ip_address
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.ip_address
     *
     * @param ipAddress the value for cabinet_V2.ip_address
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.description
     *
     * @return the value of cabinet_V2.description
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.description
     *
     * @param description the value for cabinet_V2.description
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.version
     *
     * @return the value of cabinet_V2.version
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.version
     *
     * @param version the value for cabinet_V2.version
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.lastAlive
     *
     * @return the value of cabinet_V2.lastAlive
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Date getLastalive() {
        return lastalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.lastAlive
     *
     * @param lastalive the value for cabinet_V2.lastAlive
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setLastalive(Date lastalive) {
        this.lastalive = lastalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.lastSync
     *
     * @return the value of cabinet_V2.lastSync
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Date getLastsync() {
        return lastsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.lastSync
     *
     * @param lastsync the value for cabinet_V2.lastSync
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setLastsync(Date lastsync) {
        this.lastsync = lastsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.location_building
     *
     * @return the value of cabinet_V2.location_building
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getLocationBuilding() {
        return locationBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.location_building
     *
     * @param locationBuilding the value for cabinet_V2.location_building
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setLocationBuilding(String locationBuilding) {
        this.locationBuilding = locationBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.location_floor
     *
     * @return the value of cabinet_V2.location_floor
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getLocationFloor() {
        return locationFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.location_floor
     *
     * @param locationFloor the value for cabinet_V2.location_floor
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setLocationFloor(String locationFloor) {
        this.locationFloor = locationFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.location_zone
     *
     * @return the value of cabinet_V2.location_zone
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getLocationZone() {
        return locationZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.location_zone
     *
     * @param locationZone the value for cabinet_V2.location_zone
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setLocationZone(String locationZone) {
        this.locationZone = locationZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.axis_x
     *
     * @return the value of cabinet_V2.axis_x
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getAxisX() {
        return axisX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.axis_x
     *
     * @param axisX the value for cabinet_V2.axis_x
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAxisX(Integer axisX) {
        this.axisX = axisX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.axis_y
     *
     * @return the value of cabinet_V2.axis_y
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getAxisY() {
        return axisY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.axis_y
     *
     * @param axisY the value for cabinet_V2.axis_y
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAxisY(Integer axisY) {
        this.axisY = axisY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_V2.axis_z
     *
     * @return the value of cabinet_V2.axis_z
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getAxisZ() {
        return axisZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_V2.axis_z
     *
     * @param axisZ the value for cabinet_V2.axis_z
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAxisZ(Integer axisZ) {
        this.axisZ = axisZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cabinetId=").append(cabinetId);
        sb.append(", syncflag=").append(syncflag);
        sb.append(", name=").append(name);
        sb.append(", ipAddress=").append(ipAddress);
        sb.append(", description=").append(description);
        sb.append(", version=").append(version);
        sb.append(", lastalive=").append(lastalive);
        sb.append(", lastsync=").append(lastsync);
        sb.append(", locationBuilding=").append(locationBuilding);
        sb.append(", locationFloor=").append(locationFloor);
        sb.append(", locationZone=").append(locationZone);
        sb.append(", axisX=").append(axisX);
        sb.append(", axisY=").append(axisY);
        sb.append(", axisZ=").append(axisZ);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}