package com.pxccn.PxcDali2.server.database.model;

import java.io.Serializable;

public class PointsV2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.cabinet_ID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer cabinetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.pointStr
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String pointstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.type
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.busIndex
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer busindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.busType
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String bustype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.description
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.sourceTrigger
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Boolean sourcetrigger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.filter
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String filter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.axis_x
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer axisX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.axis_y
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer axisY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_V2.axis_z
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer axisZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table points_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.cabinet_ID
     *
     * @return the value of points_V2.cabinet_ID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getCabinetId() {
        return cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.cabinet_ID
     *
     * @param cabinetId the value for points_V2.cabinet_ID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setCabinetId(Integer cabinetId) {
        this.cabinetId = cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.pointStr
     *
     * @return the value of points_V2.pointStr
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getPointstr() {
        return pointstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.pointStr
     *
     * @param pointstr the value for points_V2.pointStr
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setPointstr(String pointstr) {
        this.pointstr = pointstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.type
     *
     * @return the value of points_V2.type
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.type
     *
     * @param type the value for points_V2.type
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.busIndex
     *
     * @return the value of points_V2.busIndex
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getBusindex() {
        return busindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.busIndex
     *
     * @param busindex the value for points_V2.busIndex
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setBusindex(Integer busindex) {
        this.busindex = busindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.busType
     *
     * @return the value of points_V2.busType
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getBustype() {
        return bustype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.busType
     *
     * @param bustype the value for points_V2.busType
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setBustype(String bustype) {
        this.bustype = bustype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.name
     *
     * @return the value of points_V2.name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.name
     *
     * @param name the value for points_V2.name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.description
     *
     * @return the value of points_V2.description
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.description
     *
     * @param description the value for points_V2.description
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.sourceTrigger
     *
     * @return the value of points_V2.sourceTrigger
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Boolean getSourcetrigger() {
        return sourcetrigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.sourceTrigger
     *
     * @param sourcetrigger the value for points_V2.sourceTrigger
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setSourcetrigger(Boolean sourcetrigger) {
        this.sourcetrigger = sourcetrigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.filter
     *
     * @return the value of points_V2.filter
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getFilter() {
        return filter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.filter
     *
     * @param filter the value for points_V2.filter
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setFilter(String filter) {
        this.filter = filter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.axis_x
     *
     * @return the value of points_V2.axis_x
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getAxisX() {
        return axisX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.axis_x
     *
     * @param axisX the value for points_V2.axis_x
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAxisX(Integer axisX) {
        this.axisX = axisX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.axis_y
     *
     * @return the value of points_V2.axis_y
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getAxisY() {
        return axisY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.axis_y
     *
     * @param axisY the value for points_V2.axis_y
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAxisY(Integer axisY) {
        this.axisY = axisY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_V2.axis_z
     *
     * @return the value of points_V2.axis_z
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getAxisZ() {
        return axisZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_V2.axis_z
     *
     * @param axisZ the value for points_V2.axis_z
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAxisZ(Integer axisZ) {
        this.axisZ = axisZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_V2
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cabinetId=").append(cabinetId);
        sb.append(", pointstr=").append(pointstr);
        sb.append(", type=").append(type);
        sb.append(", busindex=").append(busindex);
        sb.append(", bustype=").append(bustype);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", sourcetrigger=").append(sourcetrigger);
        sb.append(", filter=").append(filter);
        sb.append(", axisX=").append(axisX);
        sb.append(", axisY=").append(axisY);
        sb.append(", axisZ=").append(axisZ);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}