package com.pxccn.PxcDali2.server.database.model;

import java.util.ArrayList;
import java.util.List;

public class RoomTriggerV3Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public RoomTriggerV3Example() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTriggeruuidIsNull() {
            addCriterion("triggerUUID is null");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidIsNotNull() {
            addCriterion("triggerUUID is not null");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidEqualTo(String value) {
            addCriterion("triggerUUID =", value, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidNotEqualTo(String value) {
            addCriterion("triggerUUID <>", value, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidGreaterThan(String value) {
            addCriterion("triggerUUID >", value, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidGreaterThanOrEqualTo(String value) {
            addCriterion("triggerUUID >=", value, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidLessThan(String value) {
            addCriterion("triggerUUID <", value, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidLessThanOrEqualTo(String value) {
            addCriterion("triggerUUID <=", value, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidLike(String value) {
            addCriterion("triggerUUID like", value, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidNotLike(String value) {
            addCriterion("triggerUUID not like", value, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidIn(List<String> values) {
            addCriterion("triggerUUID in", values, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidNotIn(List<String> values) {
            addCriterion("triggerUUID not in", values, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidBetween(String value1, String value2) {
            addCriterion("triggerUUID between", value1, value2, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggeruuidNotBetween(String value1, String value2) {
            addCriterion("triggerUUID not between", value1, value2, "triggeruuid");
            return (Criteria) this;
        }

        public Criteria andTriggertypeIsNull() {
            addCriterion("triggerType is null");
            return (Criteria) this;
        }

        public Criteria andTriggertypeIsNotNull() {
            addCriterion("triggerType is not null");
            return (Criteria) this;
        }

        public Criteria andTriggertypeEqualTo(String value) {
            addCriterion("triggerType =", value, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeNotEqualTo(String value) {
            addCriterion("triggerType <>", value, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeGreaterThan(String value) {
            addCriterion("triggerType >", value, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeGreaterThanOrEqualTo(String value) {
            addCriterion("triggerType >=", value, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeLessThan(String value) {
            addCriterion("triggerType <", value, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeLessThanOrEqualTo(String value) {
            addCriterion("triggerType <=", value, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeLike(String value) {
            addCriterion("triggerType like", value, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeNotLike(String value) {
            addCriterion("triggerType not like", value, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeIn(List<String> values) {
            addCriterion("triggerType in", values, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeNotIn(List<String> values) {
            addCriterion("triggerType not in", values, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeBetween(String value1, String value2) {
            addCriterion("triggerType between", value1, value2, "triggertype");
            return (Criteria) this;
        }

        public Criteria andTriggertypeNotBetween(String value1, String value2) {
            addCriterion("triggerType not between", value1, value2, "triggertype");
            return (Criteria) this;
        }

        public Criteria andRoomuuidIsNull() {
            addCriterion("roomUUID is null");
            return (Criteria) this;
        }

        public Criteria andRoomuuidIsNotNull() {
            addCriterion("roomUUID is not null");
            return (Criteria) this;
        }

        public Criteria andRoomuuidEqualTo(String value) {
            addCriterion("roomUUID =", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidNotEqualTo(String value) {
            addCriterion("roomUUID <>", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidGreaterThan(String value) {
            addCriterion("roomUUID >", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidGreaterThanOrEqualTo(String value) {
            addCriterion("roomUUID >=", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidLessThan(String value) {
            addCriterion("roomUUID <", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidLessThanOrEqualTo(String value) {
            addCriterion("roomUUID <=", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidLike(String value) {
            addCriterion("roomUUID like", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidNotLike(String value) {
            addCriterion("roomUUID not like", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidIn(List<String> values) {
            addCriterion("roomUUID in", values, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidNotIn(List<String> values) {
            addCriterion("roomUUID not in", values, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidBetween(String value1, String value2) {
            addCriterion("roomUUID between", value1, value2, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidNotBetween(String value1, String value2) {
            addCriterion("roomUUID not between", value1, value2, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIsNull() {
            addCriterion("cabinet_ID is null");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIsNotNull() {
            addCriterion("cabinet_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCabinetIdEqualTo(Integer value) {
            addCriterion("cabinet_ID =", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotEqualTo(Integer value) {
            addCriterion("cabinet_ID <>", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdGreaterThan(Integer value) {
            addCriterion("cabinet_ID >", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cabinet_ID >=", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdLessThan(Integer value) {
            addCriterion("cabinet_ID <", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdLessThanOrEqualTo(Integer value) {
            addCriterion("cabinet_ID <=", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIn(List<Integer> values) {
            addCriterion("cabinet_ID in", values, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotIn(List<Integer> values) {
            addCriterion("cabinet_ID not in", values, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdBetween(Integer value1, Integer value2) {
            addCriterion("cabinet_ID between", value1, value2, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cabinet_ID not between", value1, value2, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureIsNull() {
            addCriterion("triggerConfigure is null");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureIsNotNull() {
            addCriterion("triggerConfigure is not null");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureEqualTo(String value) {
            addCriterion("triggerConfigure =", value, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureNotEqualTo(String value) {
            addCriterion("triggerConfigure <>", value, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureGreaterThan(String value) {
            addCriterion("triggerConfigure >", value, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureGreaterThanOrEqualTo(String value) {
            addCriterion("triggerConfigure >=", value, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureLessThan(String value) {
            addCriterion("triggerConfigure <", value, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureLessThanOrEqualTo(String value) {
            addCriterion("triggerConfigure <=", value, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureLike(String value) {
            addCriterion("triggerConfigure like", value, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureNotLike(String value) {
            addCriterion("triggerConfigure not like", value, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureIn(List<String> values) {
            addCriterion("triggerConfigure in", values, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureNotIn(List<String> values) {
            addCriterion("triggerConfigure not in", values, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureBetween(String value1, String value2) {
            addCriterion("triggerConfigure between", value1, value2, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andTriggerconfigureNotBetween(String value1, String value2) {
            addCriterion("triggerConfigure not between", value1, value2, "triggerconfigure");
            return (Criteria) this;
        }

        public Criteria andFbIsNull() {
            addCriterion("fb is null");
            return (Criteria) this;
        }

        public Criteria andFbIsNotNull() {
            addCriterion("fb is not null");
            return (Criteria) this;
        }

        public Criteria andFbEqualTo(String value) {
            addCriterion("fb =", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbNotEqualTo(String value) {
            addCriterion("fb <>", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbGreaterThan(String value) {
            addCriterion("fb >", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbGreaterThanOrEqualTo(String value) {
            addCriterion("fb >=", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbLessThan(String value) {
            addCriterion("fb <", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbLessThanOrEqualTo(String value) {
            addCriterion("fb <=", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbLike(String value) {
            addCriterion("fb like", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbNotLike(String value) {
            addCriterion("fb not like", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbIn(List<String> values) {
            addCriterion("fb in", values, "fb");
            return (Criteria) this;
        }

        public Criteria andFbNotIn(List<String> values) {
            addCriterion("fb not in", values, "fb");
            return (Criteria) this;
        }

        public Criteria andFbBetween(String value1, String value2) {
            addCriterion("fb between", value1, value2, "fb");
            return (Criteria) this;
        }

        public Criteria andFbNotBetween(String value1, String value2) {
            addCriterion("fb not between", value1, value2, "fb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_trigger_V3
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 26 22:36:19 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_trigger_V3
     *
     * @mbg.generated Sun Jun 26 22:36:19 CST 2022
     */
    public static class Criterion {
        private final String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private final String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}