package com.pxccn.PxcDali2.server.database.model;

import java.io.Serializable;

public class RoomUnitV3 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.roomUUID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String roomuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.description
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.building
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String building;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.floor
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.zone
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private String zone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.axis_x
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer axisX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.axis_y
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer axisY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.axis_z
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer axisZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_unit_V3.status
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.roomUUID
     *
     * @return the value of room_unit_V3.roomUUID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getRoomuuid() {
        return roomuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.roomUUID
     *
     * @param roomuuid the value for room_unit_V3.roomUUID
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setRoomuuid(String roomuuid) {
        this.roomuuid = roomuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.name
     *
     * @return the value of room_unit_V3.name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.name
     *
     * @param name the value for room_unit_V3.name
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.description
     *
     * @return the value of room_unit_V3.description
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.description
     *
     * @param description the value for room_unit_V3.description
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.building
     *
     * @return the value of room_unit_V3.building
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getBuilding() {
        return building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.building
     *
     * @param building the value for room_unit_V3.building
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setBuilding(String building) {
        this.building = building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.floor
     *
     * @return the value of room_unit_V3.floor
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.floor
     *
     * @param floor the value for room_unit_V3.floor
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setFloor(String floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.zone
     *
     * @return the value of room_unit_V3.zone
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.zone
     *
     * @param zone the value for room_unit_V3.zone
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setZone(String zone) {
        this.zone = zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.axis_x
     *
     * @return the value of room_unit_V3.axis_x
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getAxisX() {
        return axisX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.axis_x
     *
     * @param axisX the value for room_unit_V3.axis_x
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAxisX(Integer axisX) {
        this.axisX = axisX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.axis_y
     *
     * @return the value of room_unit_V3.axis_y
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getAxisY() {
        return axisY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.axis_y
     *
     * @param axisY the value for room_unit_V3.axis_y
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAxisY(Integer axisY) {
        this.axisY = axisY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.axis_z
     *
     * @return the value of room_unit_V3.axis_z
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getAxisZ() {
        return axisZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.axis_z
     *
     * @param axisZ the value for room_unit_V3.axis_z
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setAxisZ(Integer axisZ) {
        this.axisZ = axisZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_unit_V3.status
     *
     * @return the value of room_unit_V3.status
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_unit_V3.status
     *
     * @param status the value for room_unit_V3.status
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roomuuid=").append(roomuuid);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", building=").append(building);
        sb.append(", floor=").append(floor);
        sb.append(", zone=").append(zone);
        sb.append(", axisX=").append(axisX);
        sb.append(", axisY=").append(axisY);
        sb.append(", axisZ=").append(axisZ);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}