package com.pxccn.PxcDali2.server.database.model;

import java.util.ArrayList;
import java.util.List;

public class RoomUnitV3Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public RoomUnitV3Example() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoomuuidIsNull() {
            addCriterion("roomUUID is null");
            return (Criteria) this;
        }

        public Criteria andRoomuuidIsNotNull() {
            addCriterion("roomUUID is not null");
            return (Criteria) this;
        }

        public Criteria andRoomuuidEqualTo(String value) {
            addCriterion("roomUUID =", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidNotEqualTo(String value) {
            addCriterion("roomUUID <>", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidGreaterThan(String value) {
            addCriterion("roomUUID >", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidGreaterThanOrEqualTo(String value) {
            addCriterion("roomUUID >=", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidLessThan(String value) {
            addCriterion("roomUUID <", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidLessThanOrEqualTo(String value) {
            addCriterion("roomUUID <=", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidLike(String value) {
            addCriterion("roomUUID like", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidNotLike(String value) {
            addCriterion("roomUUID not like", value, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidIn(List<String> values) {
            addCriterion("roomUUID in", values, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidNotIn(List<String> values) {
            addCriterion("roomUUID not in", values, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidBetween(String value1, String value2) {
            addCriterion("roomUUID between", value1, value2, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andRoomuuidNotBetween(String value1, String value2) {
            addCriterion("roomUUID not between", value1, value2, "roomuuid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andBuildingIsNull() {
            addCriterion("building is null");
            return (Criteria) this;
        }

        public Criteria andBuildingIsNotNull() {
            addCriterion("building is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingEqualTo(String value) {
            addCriterion("building =", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingNotEqualTo(String value) {
            addCriterion("building <>", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingGreaterThan(String value) {
            addCriterion("building >", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingGreaterThanOrEqualTo(String value) {
            addCriterion("building >=", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingLessThan(String value) {
            addCriterion("building <", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingLessThanOrEqualTo(String value) {
            addCriterion("building <=", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingLike(String value) {
            addCriterion("building like", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingNotLike(String value) {
            addCriterion("building not like", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingIn(List<String> values) {
            addCriterion("building in", values, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingNotIn(List<String> values) {
            addCriterion("building not in", values, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingBetween(String value1, String value2) {
            addCriterion("building between", value1, value2, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingNotBetween(String value1, String value2) {
            addCriterion("building not between", value1, value2, "building");
            return (Criteria) this;
        }

        public Criteria andFloorIsNull() {
            addCriterion("floor is null");
            return (Criteria) this;
        }

        public Criteria andFloorIsNotNull() {
            addCriterion("floor is not null");
            return (Criteria) this;
        }

        public Criteria andFloorEqualTo(String value) {
            addCriterion("floor =", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotEqualTo(String value) {
            addCriterion("floor <>", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorGreaterThan(String value) {
            addCriterion("floor >", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorGreaterThanOrEqualTo(String value) {
            addCriterion("floor >=", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLessThan(String value) {
            addCriterion("floor <", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLessThanOrEqualTo(String value) {
            addCriterion("floor <=", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLike(String value) {
            addCriterion("floor like", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotLike(String value) {
            addCriterion("floor not like", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorIn(List<String> values) {
            addCriterion("floor in", values, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotIn(List<String> values) {
            addCriterion("floor not in", values, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorBetween(String value1, String value2) {
            addCriterion("floor between", value1, value2, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotBetween(String value1, String value2) {
            addCriterion("floor not between", value1, value2, "floor");
            return (Criteria) this;
        }

        public Criteria andZoneIsNull() {
            addCriterion("zone is null");
            return (Criteria) this;
        }

        public Criteria andZoneIsNotNull() {
            addCriterion("zone is not null");
            return (Criteria) this;
        }

        public Criteria andZoneEqualTo(String value) {
            addCriterion("zone =", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotEqualTo(String value) {
            addCriterion("zone <>", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThan(String value) {
            addCriterion("zone >", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThanOrEqualTo(String value) {
            addCriterion("zone >=", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLessThan(String value) {
            addCriterion("zone <", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLessThanOrEqualTo(String value) {
            addCriterion("zone <=", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLike(String value) {
            addCriterion("zone like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotLike(String value) {
            addCriterion("zone not like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneIn(List<String> values) {
            addCriterion("zone in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotIn(List<String> values) {
            addCriterion("zone not in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneBetween(String value1, String value2) {
            addCriterion("zone between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotBetween(String value1, String value2) {
            addCriterion("zone not between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andAxisXIsNull() {
            addCriterion("axis_x is null");
            return (Criteria) this;
        }

        public Criteria andAxisXIsNotNull() {
            addCriterion("axis_x is not null");
            return (Criteria) this;
        }

        public Criteria andAxisXEqualTo(Integer value) {
            addCriterion("axis_x =", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXNotEqualTo(Integer value) {
            addCriterion("axis_x <>", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXGreaterThan(Integer value) {
            addCriterion("axis_x >", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_x >=", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXLessThan(Integer value) {
            addCriterion("axis_x <", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXLessThanOrEqualTo(Integer value) {
            addCriterion("axis_x <=", value, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXIn(List<Integer> values) {
            addCriterion("axis_x in", values, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXNotIn(List<Integer> values) {
            addCriterion("axis_x not in", values, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXBetween(Integer value1, Integer value2) {
            addCriterion("axis_x between", value1, value2, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisXNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_x not between", value1, value2, "axisX");
            return (Criteria) this;
        }

        public Criteria andAxisYIsNull() {
            addCriterion("axis_y is null");
            return (Criteria) this;
        }

        public Criteria andAxisYIsNotNull() {
            addCriterion("axis_y is not null");
            return (Criteria) this;
        }

        public Criteria andAxisYEqualTo(Integer value) {
            addCriterion("axis_y =", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYNotEqualTo(Integer value) {
            addCriterion("axis_y <>", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYGreaterThan(Integer value) {
            addCriterion("axis_y >", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_y >=", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYLessThan(Integer value) {
            addCriterion("axis_y <", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYLessThanOrEqualTo(Integer value) {
            addCriterion("axis_y <=", value, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYIn(List<Integer> values) {
            addCriterion("axis_y in", values, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYNotIn(List<Integer> values) {
            addCriterion("axis_y not in", values, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYBetween(Integer value1, Integer value2) {
            addCriterion("axis_y between", value1, value2, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisYNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_y not between", value1, value2, "axisY");
            return (Criteria) this;
        }

        public Criteria andAxisZIsNull() {
            addCriterion("axis_z is null");
            return (Criteria) this;
        }

        public Criteria andAxisZIsNotNull() {
            addCriterion("axis_z is not null");
            return (Criteria) this;
        }

        public Criteria andAxisZEqualTo(Integer value) {
            addCriterion("axis_z =", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZNotEqualTo(Integer value) {
            addCriterion("axis_z <>", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZGreaterThan(Integer value) {
            addCriterion("axis_z >", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZGreaterThanOrEqualTo(Integer value) {
            addCriterion("axis_z >=", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZLessThan(Integer value) {
            addCriterion("axis_z <", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZLessThanOrEqualTo(Integer value) {
            addCriterion("axis_z <=", value, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZIn(List<Integer> values) {
            addCriterion("axis_z in", values, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZNotIn(List<Integer> values) {
            addCriterion("axis_z not in", values, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZBetween(Integer value1, Integer value2) {
            addCriterion("axis_z between", value1, value2, "axisZ");
            return (Criteria) this;
        }

        public Criteria andAxisZNotBetween(Integer value1, Integer value2) {
            addCriterion("axis_z not between", value1, value2, "axisZ");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_unit_V3
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 18 10:18:42 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_unit_V3
     *
     * @mbg.generated Mon Jul 18 10:18:42 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}